# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d5987ea5083681703b7140f5f7e6138060cca871e5312a02e1867be5bcff099e0f0c6a7d82477d562bb850de06dd2e59635bd514323eb601f3f7a65ab8ffca0

test:
  secret_key_base: f91f051fd0d0cd96f45c0cd708dd332ac085cba906f33bb72b5ca467f0a9619fb527e5998a6a83a666d002e76a6b43afe02b6e62ec941b0b13c8d18ed8b07800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
